"""empty message

Revision ID: 0f406263fbd6
Revises: 
Create Date: 2020-11-23 15:53:07.693921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f406263fbd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_candidate_name'), 'candidate', ['name'], unique=False)
    op.add_column('contribution_source', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('contribution_source', 'title')
    op.add_column('contributor', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_contributor_name'), 'contributor', ['name'], unique=False)
    op.add_column('government', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_government_name'), 'government', ['name'], unique=False)
    op.drop_index('ix_government_government_name', table_name='government')
    op.drop_column('government', 'government_name')
    op.add_column('office', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_office_name'), 'office', ['name'], unique=False)
    op.drop_index('ix_office_office_name', table_name='office')
    op.drop_column('office', 'office_name')
    op.add_column('party', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_party_name'), 'party', ['name'], unique=False)
    op.drop_index('ix_party_party_name', table_name='party')
    op.drop_column('party', 'party_name')
    op.add_column('treasurer', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_treasurer_name'), 'treasurer', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treasurer_name'), table_name='treasurer')
    op.drop_column('treasurer', 'name')
    op.add_column('party', sa.Column('party_name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_party_party_name', 'party', ['party_name'], unique=False)
    op.drop_index(op.f('ix_party_name'), table_name='party')
    op.drop_column('party', 'name')
    op.add_column('office', sa.Column('office_name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_office_office_name', 'office', ['office_name'], unique=False)
    op.drop_index(op.f('ix_office_name'), table_name='office')
    op.drop_column('office', 'name')
    op.add_column('government', sa.Column('government_name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_government_government_name', 'government', ['government_name'], unique=False)
    op.drop_index(op.f('ix_government_name'), table_name='government')
    op.drop_column('government', 'name')
    op.drop_index(op.f('ix_contributor_name'), table_name='contributor')
    op.drop_column('contributor', 'name')
    op.add_column('contribution_source', sa.Column('title', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('contribution_source', 'name')
    op.drop_index(op.f('ix_candidate_name'), table_name='candidate')
    op.drop_column('candidate', 'name')
    # ### end Alembic commands ###
